# [[plugins]]
# repo = ''
# hook_add = ''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'davidhalter/jedi'
on_ft = 'py'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'py'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'KKPMW/moonshine-vim'
hook_add = 'colorscheme moonshine'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'w0rp/ale'
